spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/eolink?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  resources:
    static-locations: claspath:dump/, file:dump/, classpath:config/, file:config/

  devtools:
    restart:
      exclude: dump/**
  #设置spring-boot 编码格式
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    converters:
      preferred-json-mapper: fastjson

  messages:
    encoding: UTF-8

#启用shutdown
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    shutdown.enabled: true

# 日志
logging:
  level:
    org.springframework: WARN
    com.eolinker.*: DEBUG
  file: logs/debug.log


server:
  port: 8088
  servlet:
    context-path: /eolinker_os

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.eolinker.pojo
